# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-30 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(default=b'b2ea181e-1581-11e7-a646-6cc217e9b519', editable=False, max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='e_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(default=b'b2e954d1-1581-11e7-95bc-6cc217e9b519', editable=False, max_length=100)),
                ('screen_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('pic_url', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10)),
                ('ethnicity', models.CharField(max_length=50)),
                ('u_type', models.CharField(choices=[('general', 'general'), ('hunters', 'hunters'), ('premium', 'premium')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='editor_pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
            options={
                'ordering': ('score',),
            },
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(default=b'b2e9a2f0-1581-11e7-9f42-6cc217e9b519', editable=False, max_length=100)),
                ('issue', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash_tag', models.CharField(blank=True, max_length=30)),
                ('topic_type', models.CharField(choices=[('politics', 'politics'), ('tech', 'tech'), ('startup', 'startup')], max_length=30)),
                ('comment_permission', models.ManyToManyField(blank=True, related_name='comment_permission', to='handler.e_user')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.e_user')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='t_downvotes', to='handler.e_user')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='t_upvotes', to='handler.e_user')),
            ],
        ),
        migrations.AddField(
            model_name='editor_pick',
            name='editor_topics',
            field=models.ManyToManyField(to='handler.topic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='c_shares', to='handler.e_user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.topic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='c_upvotes', to='handler.e_user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.e_user'),
        ),
    ]
