# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_id',
            field=models.CharField(default=b'c34b83c0-1581-11e7-8f21-6cc217e9b519', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='e_user',
            name='u_id',
            field=models.CharField(default=b'c34a724f-1581-11e7-a553-6cc217e9b519', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='t_id',
            field=models.CharField(default=b'c34ac070-1581-11e7-9ea0-6cc217e9b519', editable=False, max_length=100),
        ),
    ]
